### ISSUE TITLE
Question: Why Blake2 and not Keccak?

### ISSUE THREAD

**Issue by collincusce** [ethereum/beacon_chain#1]
Both would work. Just curious.

**Comment by djrtwo** [comment]
Blake2 is faster https://blake2.net/.
One of the major bottlenecks in sharding/ffg is signature verification. Utilizing blake2 will allow us to process more validator signatures ==> increase the theoretical maximum validators the system can support.

**Comment by collincusce** [comment]
Ah another reason I asked is because blake2 isn't in solidity, ya? keccak, sha256, and ripemd? I figured it might be nice for contracts to reference state roots, but in hindsight, it shouldn't make a difference. Thanks!

**Comment by corpetty** [comment]
Keccak is also more efficient in ASIC creation, as per one of the authors of BLAKE2: https://crypto.stackexchange.com/questions/31674/what-advantages-does-keccak-sha-3-have-over-blake2

**Comment by djrtwo** [comment]
It is not in solidity/evm, but the state root references can be embedded in solidity/evm but they just can't be efficiently calculated there.

**Comment by chriseth** [comment]
There is already a proposal to add a precompiled contract for blake2 and I guess it having significance for ethereum itself would be a reason enough to add it as a precompile.
