### ISSUE TITLE
update logic for crosslink notaries

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#10]
# Issue
The logic for crosslink notaries in the current implementation is lacking. It assumes we will be able to go through every shard every epoch. This is not actually the case because there is to be a fixed number of notaries (`NOTARIES_PER_CROSSLINK`) per crosslink, but a constant number of shards and variable number of validators. 

# Proposed Implementation
- Add global var `NOTARIES_PER_CROSSLINK`
- add helper function `get_crosslink_shards` to get the shards that should be crosslinked this epoch
- add helper function `get_crosslink_notaries` to get the validators that should notarize the given shard for this epoch.
- remove helper function `get_shard_attesters` (superseded with `get_crosslink_notaries`)
- utilize these helper functions to limit the work to be done by validators on shards per epoch. _do not_ accept crosslinks for shards not in `get_crosslink_shards`

Implementations of the helper functions are approximately the following:
```python
def get_crosslink_shards(crystallized_state):
    start_from = crystallized_state.next_shard
    count = len(crystallized_state.active_validators) // NOTARIES_PER_CROSSLINK
    if start_from + count <= SHARD_COUNT:
        return list(range(s, s+count))
    else:
        return list(range(start_from, SHARD_COUNT)) + list(range(start_from + count - SHARD_COUNT))
```

```python
def get_crosslink_notaries(crystallized_state, shard_id):
    crosslink_shards = get_crosslink_shards(crystallized_state)
    if shard_id not in crosslink_shards:
        return None
    all = len(crystallized_state.current_shuffling)
    start = all * crosslink_shards.index(shard_id) // len(crosslink_shards)
    end = all * (crosslink_shards.index(shard_id)+1) // len(crosslink_shards)
    return crystallized_state.current_shuffling[start: end]
```

**Comment by hwwhww** [comment]
Would like to work on this

**Comment by djrtwo** [comment]
I'll get my PR merged shortly
