### ISSUE TITLE
Block processing time estimates at scale

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#103]
# Issue
In the last eth2.0 implementers call, we decided it would be worthwhile to run some timing analysis on processing blocks with real-world amounts of attestations.

It would be great to get results from at least one other client. I know not everyone has a working BLS aggregate implementation yet, but anyone that does should give this a try and report results.

# Proposed Implementation
Assuming 10M eth deposited puts us at ~300k validators. With 64 slots, that is ~5000 validators per slot. With 1000 shards divided across the 64 slots, that is ~16 shards per slot.

If all of the validators coordinate and vote on the same crosslink and their attestations are aggregated and include in the next slot, then there will be 16 attestations of ~300 validators each per block. This is a good place to start.

We can then make this estimate a worse case by assuming the validators split their votes across 2, 3, 4, or even 5 different crosslink candidates. If all committees split their votes across 2 candidates, then there would be 32 attestations per block each with ~150 validators each.

*EDIT*
My estimates on number of committees and size of committees were a bit off in practice. When using `BenchmarkParams { total_validators: 312500, cycle_length: 64, shard_count: 1024, shards_per_slot: 16, validators_per_shard: 305, min_committee_size: 128 }`, each slot has approximately 20 committees of size 244 (rather than 16 of ~300). This shouldn't drastically change the output, but is a better target because it reflects the actual shuffling alg
(cc: @paulhauner)

*EDIT2*
My original assumption was correct and the spec was incorrect! Go with the original estimates

**Comment by paulhauner** [comment]
Here are some timings from Lighthouse (I'll add @djrtwo's first scenario once I complete it):

Computer: Lenovo X1 Carbon 5th Gen with an Intel i5-7300U @ 2.60GHz running Arch Linux with each core idling around 2-8% before tests.

| | | | | |
|------------------|----------------------------|------------------|----------------|-----------------------|
| num_attestations | validators_per_attestation | total_validators | total_deposits | block_process_seconds |
| 2 | 244 | 31250 | 1000000 | N/A |
| 16 | 305 | 312500 | 10000000 | 0.066773104 |
| 16 | 3051 | 3125000 | 100000000 | 0.249065226 |

Note: this is using an in-memory database. @djrtwo were you using an on-disk DB at all?

**Comment by djrtwo** [comment]
No on-disk DB for ours

**Comment by djrtwo** [comment]
Curious about if you see a closer 10x different when you remove the concurrency @paulhauner

**Comment by paulhauner** [comment]
Without concurrency:

| | | | | |
|------------------|----------------------------|------------------|----------------|-----------------------|
| num_attestations | validators_per_attestation | total_validators | total_deposits | block_process_seconds |
| 2 | 244 | 31250 | 1000000 | N/A |
| 16 | 305 | 312500 | 10000000 | 0.125273217 |
| 16 | 3051 | 3125000 | 100000000 | 0.450318683 |

That ~4x difference still holds.

In these benches I'm starting with a SSZ serialized block and then de-serializing it (and all the `AttestationRecords`) inside this benchmark. Are you doing the same thing @djrtwo? If not, maybe we're seeing a constant SSZ de-serialization overhead in lighthouse that we're not seeing in beacon_chain?

**Comment by djrtwo** [comment]
That's it. I'm not clocking the deserialization. 

Both are interesting numbers. I was looking specifically for block validity and primarily at the signatures because this was our estimated bottleneck when designing the protocol. 

Let's see what it is without the deserialize.

**Comment by kaibakker** [comment]
Looks great! Would performance increase when a `vote` wouldn't include a `source` as described here: https://ethresear.ch/t/should-we-simplify-casper-votes-to-remove-the-source-param/3549 ?
