### ISSUE TITLE
remove `total_deposits` from CrystallizedState

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#104]
# Issue
The v2.1 spec no longer has the field `total_deposits` in `CrystallizedState`.

# Proposed Implementation
- remove from state, tests, etc
- calculate on the fly anytime where needed

**Comment by johnsBeharry** [comment]
Currently implementing this change.
FYI seems like `total_deposit` calculation needs to be done primarily for `initialize_new_cycle()`.
