### ISSUE TITLE
ssz intX type is actually uint

### ISSUE THREAD

**Issue by darrenlangley** [ethereum/beacon_chain#112]
Hi all,

I noticed that ssz (https://github.com/ethereum/beacon_chain/blob/master/ssz/ssz.py) treats the type intX more like a uint rather than an int.

This works fine when signed int usually go between -128 to 128:
```
typ = 'int8'
value = 255
print(serialize(value, typ))
```

Also this errors with overflow:
```
typ = 'int8'
value = -1
print(serialize(value, typ))
```

If this is expected than cool, although it is a bit confusing calling it int rather than uint.

**Comment by djrtwo** [comment]
This lack of clarity has come up a few times over the past week. I believe we should probably support `uint` vs `int` explicitly.
