### ISSUE TITLE
Randao reveal verification

### ISSUE THREAD

**Issue by hwwhww** [ethereum/beacon_chain#12]
# Issue
As this line said: https://github.com/ethereum/beacon_chain/blob/29fb10e49b76eaf1d9be20f0a39e0406620ef809/beacon_chain/state/state_transition.py#L371

# How to fix it?
The concept is described in the spec: https://notes.ethereum.org/s/Syj3QZSxm#Miscellaneous
The `RecentProposerRecord` part depends on #7.

**Comment by jannikluhn** [comment]
I've looked into this a little. This seems to be blocked by missing specification on the used hash function and the required/allowed "hashing depth" of the commitment.

**Comment by hwwhww** [comment]
Per @vbuterin and @JustinDrake 's suggestion, since the RNG process has not been finalized yet (exploring RANDAO + VDF), we can just use blockhash for generation randomness for now if it's a bottleneck.
