### ISSUE TITLE
enforce maximum committees per slot

### ISSUE THREAD

**Issue by hwwhww** [ethereum/beacon_chain#125]
### Issue
As https://github.com/ethereum/eth2.0-specs/pull/12, the maximum number of committees per slot should not exceed `SHARD_COUNT // CYCLE_LENGTH`

### Proposed Implementation
Update `get_new_shuffling` function as the spec:
`committees_per_slot = len(avs) // cycle_length // (min_committee_size * 2) + 1` -> `committees_per_slot = min(len(avs) // cycle_length // (min_committee_size * 2) + 1, shard_count // cycle_length)`

**Comment by djrtwo** [comment]
Probably want a test here that shows even `len(avs)` gets really big that the total number of committees output by the shuffling is never greater than shard_count
