### ISSUE TITLE
`get_shuffling` can't handle `sample` larger than `validator_count`

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#18]
# Issue
`get_shuffling` can't handle when `sample` larger than `validator_count`. The algorithm does an infinite loop. This actually occurs in code when `len(active_validators)` is less than `ATTESTER_COUNT` and `get_attesters_and_signer` is called.

# Proposed Implementation
stub: need to think more

probably do one of the following:
- prevent this from happening with an assertion
- wrap shuffling array around to be the length of `sample`

**Comment by hwwhww** [comment]
It seems good to set the `MINIMUM_VALIDATOR_COUNT` for safety reason: https://ethresear.ch/t/safe-notary-pool-size/1728 and https://ethresear.ch/t/registrations-shard-count-and-shuffling/2129

**Comment by paulhauner** [comment]
Turns out I made a duplicate issue. I'll close it and just use this one.

FWIW, here's the suggestion I had in the duplicate issue:

```python
if active_validators < 2:
    raise Exception()

validator_requirement = config['attester_count'] + skip_count + 1

if (validator_requirement > active_validators):
     attesters = indicies[:-1]
else:
    attesters[:config['attester_count'] + skip_count]

proposer = indicies[-1]
```

I agree with the `MINIMUM_VALIDATOR_COUNT` suggestion. I guess we'd face similar issues if `skip_count` gets too high, though.

**Comment by paulhauner** [comment]
After playing around with this in Rust, my thoughts are that `get_shuffling()` shouldn't be concerned with "sampling" (i.e., getting some subset of shuffled active validators). That should be handled by whatever downstream function requires that sampling.

I'm only a little of the way into this state transition stuff so take that with a grain of salt. Just my thoughts so far.

**Comment by djrtwo** [comment]
`get_new_shuffling` in current spec does not handle sampling yay.
