### ISSUE TITLE
what get_crosslink_shards returns?

### ISSUE THREAD

**Issue by terenc3t** [ethereum/beacon_chain#23]
For the following function, what is `s` in `range(s, s+count)`? and what are we returning? is it just a list of numbered shards that get to cross link in the next epoch?

```
def get_crosslink_shards(crystallized_state):
    start_from = crystallized_state.next_shard
    count = len(crystallized_state.active_validators) // NOTARIES_PER_CROSSLINK
    if start_from + count <= SHARD_COUNT:
        return list(range(s, s+count))
    else:
        return list(range(start_from, SHARD_COUNT)) + list(range(start_from + count - SHARD_COUNT))
```

**Comment by hwwhww** [comment]
> what is s in range(s, s+count)?

`s` is `start_from`, typo.

> is it just a list of numbered shards that get to cross link in the next epoch?

I think so, a list of simplified `shard_id`s.

**Comment by terenc3t** [comment]
Thanks for the explanations!
