### ISSUE TITLE
Reorg the helper functions

### ISSUE THREAD

**Issue by hwwhww** [ethereum/beacon_chain#24]
# Issue
There are some state transition helper functions are [described in the spec](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ#Helper-functions) especially. Reorg them together into `helpers.py` can help to improve readability.

# Proposed implementation
1. Basically, follow the spec:
    1. `get_shuffling`: has been implemented, 
    2. `get_attesters_and_proposer`: implemented in #16
    3. `get_crosslink_shards`: #10
    4. `get_crosslink_notaries`: #10
2. Add tests.

**Comment by djrtwo** [comment]
Closing due to updated spec
