### ISSUE TITLE
How are block times / confirmations impacted by this?

### ISSUE THREAD

**Issue by collincusce** [ethereum/beacon_chain#3]
Between PoS, the sharding, beacons, etc... can we model block time estimates in the notes?

Is the main chain a throttle point for block times, too? I don't think it is, because you lock value from the main chain to the beacon, but it's not 100% confirmed from my reading. There is a main_chain_ref so it could be, not sure. Halp?

**Comment by djrtwo** [comment]
The main chain and beacon chain can proceed at independent block times.

A discussion of beacon and shard block times would be better had a http://ethresear.ch
