### ISSUE TITLE
Questions about `get_shuffling()` 

### ISSUE THREAD

**Issue by paulhauner** [ethereum/beacon_chain#39]
https://github.com/ethereum/beacon_chain/blob/8192419ce78e09755812264490e404c91808596b/beacon_chain/state/state_transition.py#L59-L62

I'm going through the `get_shuffling()` function and I don't quite understand the logic here regarding `rand_max`. As I understand it, the program says presently that if `validator_count > (max_validators / 2)` then we should not shuffle and go into an infinite loop.

I assume the infinite loop thing is an extra indentation where there shouldn't be on line 62. However, I don't understand the "don't shuffle if `validator_count < rand_max` logic" (this condition is true whenever `validator_count <= (max_validators / 2)`).

Thanks! :slightly_smiling_face:

**Comment by paulhauner** [comment]
FYI I have a `get_shuffling()` implementation [here](https://github.com/sigp/rust_beacon_chain/blob/master/src/state/state_transition.rs) which expresses how I understand it should work.

**Comment by djrtwo** [comment]
Closed in favor of #18

**Comment by djrtwo** [comment]
Whoops, wrong closure

**Comment by paulhauner** [comment]
Closed in favor of https://github.com/ethereum/beacon_chain/issues/57
