### ISSUE TITLE
Initial comments, comparisons, questions

### ISSUE THREAD

**Issue by collincusce** [ethereum/beacon_chain#4]
Sorry if this isn't the best place to write this, but I don't know where else to put it.

This bares some resemblance to what DFINITY is doing, but it differs a bit. From my understanding of DFINITY, some sample of N of M validators are selected to attest the validity of the state using BLS signatures. At first read, this is really similar to what this system doing.  However, in DFINITY the consensus mechanism is decoupled from the state history. This reduces confirmation times significantly.

Alternatively, the Kadena group has created a system using graph theory which enables PoW at-scale. Since each chain structured in a graph of uniform degree N, it takes N "hops" (degree in a graph) to get to any other chain. From the context of a single chain in their "chainweb", you must have your nearest neighbors headers to create a new block. This means that all blocks are confirms in a fixed N blocks, so if degree is 3, it takes 3 blocks to confirm the entire network. This has the side effect of reducing block times significantly, because the hash power on each chain in the chainweb is enabled to be lowered significantly.... really significantly. 

I bring this up because this proposed implementation seems to have properties of both a bit, but also deviates in that it's a purely incentive-based model for validating shards. 

Like DFINITY there's a random validator selection to for committees of attesters (per block I believe, right?). This means that validation is really super selective and quick, and all you need is some fixed plurality of the attesters to validate a block. That's dope! But you're using RANDAO instead of something like threshold relay (though they're somewhat similar in idea and purpose). Why not go for a system like DFINITY. Nothing jumps out at me which prevents it. Heck the model bares very similar resemblance: https://speakerdeck.com/stringlabs/hail-the-decentralized-cloud?slide=44

Like Kadena, there's a significant incentive for load to be distributed across the shard network, but ulike Kadena there's no difficulty to maintain so it's really about processing shards and having sufficient validator pool to do so. Yet we're still throttled in some way by the main chain, no? Or ... is there a choke point? There might not be, I'm unsure. I am a bit curious what happens if validators stop participating suddenly, though, or ignore certain shards. Can they withhold against specific shards in this scheme? In Kadena, this stops the entire network, so everyone must try to balance their hashpower across the chainweb to keep the entire chainweb going. What about here? Can a shard be neglected?

**Comment by collincusce** [comment]
I think something else that's confusing me is the main_chain_ref part. It seems like we're burning coins from main chain to beacon chain, right? So will the beacon chain always depend on the main chain or is this a transition from main chain to PoS (beacon) chain?

**Comment by djrtwo** [comment]
Closing. I suggest you take this to http://ethresear.ch
