### ISSUE TITLE
Ethereum Sharding Implementers Call #0 Agenda

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#44]
## Agenda
1. General Introduction of Sharding Meeting
2. Client Updates
3. Research Updates
4. Open Discussion
    * [v2.1 spec](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ#)
    * [Conforming to p2p messages, prysmatic protocol buffers](https://github.com/ethereum/beacon_chain/issues/44#issuecomment-405298161), and other p2p related discussion
    * [BLS signature standard libraries](https://github.com/ethereum/beacon_chain/issues/44#issuecomment-405415540)
        * https://github.com/milagro-crypto/amcl/tree/master/version3
    * Current state of cross shard communication research
    * Actionable items for clients and research
    * Format/Timing of future meetings

**Comment by rauljordan** [comment]
Prysmatic Labs will be joining! Looking forward to discussing details. Currently, we have a bunch of open [issues](https://github.com/prysmaticlabs/geth-sharding) we are working on and creating design docs for around items such as fork choice rules, beacon chain sync, and more.

**Comment by prestonvanloon** [comment]
Can we discuss when/how we will conform to p2p messages? 
For Prysmatic, we're using protocol buffers that we would like to share with other clients at some point.

**Comment by Mikerah** [comment]
I will be joining on behalf of ChainSafe. We are still working on figuring out how to work in the quirks of Javascript to make this work. But, progress has been steady.

**Comment by paulhauner** [comment]
Sounds like a great idea. Myself and potentially another will join.

I'd be interested to talk about the state of libraries supporting BLS multi-sigs. Seems like there's not much out there and we'll need some trusted implementations eventually. Mainly I'd be keen to hear everyone else's experience with it.

Also keen to chat about p2p. Looking forward to hearing about Prysmatic's protocol buffers :)

**Comment by NikVolf** [comment]
Happy to join from Parity!

**Comment by cspannos** [comment]
I'd like to join, although mostly as an observer. I am researching developer practices for scaling, funded by the Ethereum Foundation May grants program, and would like to listen and take notes.
