### ISSUE TITLE
_compute_new_active_state(): does not verify block.parent_hash

### ISSUE THREAD

**Issue by paulhauner** [ethereum/beacon_chain#47]
As the title says, I can't see where `block.parent_hash` is checked in `_computer_new_active_state()` ([convenience link](https://github.com/ethereum/beacon_chain/blob/509387c5a1eb4eaa9f636ae01dedf4b340c4f09e/beacon_chain/state/state_transition.py#L395)).

I assume the check would look something like this: 
```python
assert block.parent_hash == blake(serialize(parent_block))
```

As always, keen to hear your thoughts :relaxed:

**Comment by paulhauner** [comment]
Maybe you're just assuming this is done upstream?

**Comment by paulhauner** [comment]
Oh, I just saw the updated spec doc - I'm guessing this function will get a complete re-write!

**Comment by hwwhww** [comment]
This is implicitly addressed in [Beacon chain processing](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ#Beacon-chain-processing):
> For a block on the beacon chain to be processed by a node, three conditions have to be met:
> * The parent pointed to by the parent_hash has already been processed and accepted
...

Could be implemented in #14 or other implementation approaches.

**Comment by djrtwo** [comment]
Yeah, I have a stub for this in the v2.1 update. I think I would due that validation upstream, but an assert in there wouldn't hurt...
