### ISSUE TITLE
Have you guys coded the get_cutoffs algo?

### ISSUE THREAD

**Issue by terenc3t** [ethereum/beacon_chain#48]
I'm wondering if you guys have coded the `get_cutoffs` algo to split up validators into group at the start of every epoch? that should determine at what height they can make attestations and what shard they can make crosslinks

**Comment by hwwhww** [comment]
Not yet; it only exists in the Casper+Sharding chain v2.1 spec so far.

**Comment by terenc3t** [comment]
Got it! Thanks!
