### ISSUE TITLE
Proposer power?

### ISSUE THREAD

**Issue by collincusce** [ethereum/beacon_chain#5]
How much power does a proposer on a particular shard actually have? If one of my validators was elected as a proposer on a shard that had my competitor's contract, could I propose an order of transactions which would minimize their profits but still be considered valid?

The reason I look at this differently than leader election on a single chain is because a big player (perhaps state actor) could create a lot of validators and use it to manipulate the market if they by chance got proposer status even, say, 1% of the time across each shard they have interest in manipulating (which could be a few hundred out of the entire network). On a single chain this is significantly less likely, though still very possible. I may be missing information or completely misunderstanding something fundamental though. Is this possible?

**Comment by djrtwo** [comment]
These types of attacks are largely mitigated by frequently randomly distributing and shuffling validators across shards. I would suggest asking this in http://ethresear.ch
