### ISSUE TITLE
When is epoch transition?

### ISSUE THREAD

**Issue by terenc3t** [ethereum/beacon_chain#51]
The condition to check for epoch transition described in 2.1 spec is a bit odd to me.

`The epoch transition, which happens only if slot_number >= (epoch_number + 1) // EPOCH_LENGTH`

Do you set slot number back to 0 after an epoch transition? if that's the case then every slot is an epoch transition

```python
slot_number = 0
epoch_number = 0
for i in range (0,1000):
    if slot_number >= (epoch_number + 1) // 64:
        print "epoch transition!"
        print epoch_number
        print slot_number
        epoch_number = epoch_number + 1
        slot_number = 0
    else:
        print "not a epoch transition!"
        print epoch_number
        print slot_number
    slot_number = slot_number + 1
```

**Comment by djrtwo** [comment]
Looks like maybe it should be if `slot_number >= (epoch_number + 1) * EPOCH_LENGTH`

`slot_number` is not reset every epoch. `slot_number`  accumulates across all time of the blockchain. At every 8 second, a new block _can_ be created for that slot on top of whatever the proposer sees as the head. The reason that the (fixed) logic above is such is that a block might not be created at exactly the epoch boundary in whatever fork of the chain we are looking at.

For example, suppose a `Block A` in epoch 1 is created at slot 126 and then a `Block B` is built on top of `Block A` at slot 129. This should trigger an epoch transition.
```python
slot_number = 129
epoch_number = 1
(slot_number >= (epoch_number + 1) * EPOCH_LENGTH) == True
# 129 >= (1 + 1) * 64
```

**Comment by djrtwo** [comment]
Checking to make sure that it is a bug and fixing the spec if so

**Comment by terenc3t** [comment]
Yay. Thanks for checking @djrtwo !

**Comment by djrtwo** [comment]
Confirmed bug, fixed spec. Thanks @terenc3t!

**Comment by akash-yadagouda** [comment]
What is epoch transaction in PoA of Ethereum?
I am not even sure about epoch and transaction word are related to each other.
If you guys get anything related to epoch transaction or epoch. Don't forget to ping here.
Thank you
Akash Yadagouda
India
