### ISSUE TITLE
Assert in Shuffle Function

### ISSUE THREAD

**Issue by terenc3t** [ethereum/beacon_chain#52]
Question regarding `assert len(lst) <= 16777216` in the shuffle function. The max validator count is 2^22 but 16777216 is 2*24. Is that right?

**Comment by djrtwo** [comment]
Yup 2^24 is the size of the datatype whereas 2^22 is the max validators due to imposed protocol limitations (related to approximate max ether supply and the 32 eth deposit size)

**Comment by terenc3t** [comment]
Got it!
