### ISSUE TITLE
question on get_incremented_validator_sets

### ISSUE THREAD

**Issue by terenc3t** [ethereum/beacon_chain#53]
Sorry to bother y'all again. One last question - the new crystallized state is not tracking `queued` and `exited` validator sets. How do we go through queued validators and induct them to be active, and move low-balanced active validators to exit set?

**Comment by djrtwo** [comment]
In this spec, we've moved to having a constant validator index for each validator. Whether they are `queued`, `active`, or `exited` is now just a function of `start_dynasty` and `end_dynasty`. You can loop through and grab these sets per dynasty as needed (or manage them in some other more sophisticated way).

There was some messiness in holding validators accountable (slashing) when they didn't have a fixed index. This cleans that up.

**Comment by terenc3t** [comment]
Perfect. Thanks
