### ISSUE TITLE
question on get_new_shuffling

### ISSUE THREAD

**Issue by terenc3t** [ethereum/beacon_chain#54]
Can someone explain to me what the following code does in get_new_shuffling function? I have a general idea, but want to clarify on what is `slots_per_committee` vs `committees_per_slot `? Also what are we getting with `int(len(avs) // EPOCH_LENGTH // (MIN_COMMITTEE_SIZE * 2)) + 1`?

``` 
   if len(avs) >= EPOCH_LENGTH * MIN_COMMITTEE_SIZE:
        slots_per_committee = int(len(avs) // EPOCH_LENGTH // (MIN_COMMITTEE_SIZE * 2)) + 1 
        slots_per_committee = 1
    else:
        committees_per_slot = 1
        slots_per_committee = 1
        while len(avs) * slots_per_committee < EPOCH_LENGTH * MIN_COMMITTEE_SIZE and slots_per_committee < EPOCH_LENGTH:
            slots_per_committee *= 2
```

**Comment by djrtwo** [comment]
`if len(avs) >= EPOCH_LENGTH * MIN_COMMITTEE_SIZE:`
In the case when we have more than enough active validators to have an appropriate sized committee for every slot, every committee is only in 1 slot (`slots_per_committee = 1`), but there might be multiple committees per slot (`committees_per_slot = int(len(avs) // EPOCH_LENGTH // (MIN_COMMITTEE_SIZE * 2)) + 1 `)

`else:`
There are only one committee in each slot (`committees_per_slot = 1`), and each committee might actually have to attest to more than one slot (thus the while loop to figure out how many slots each committee needs to attest to)

**Comment by djrtwo** [comment]
Let me know if you want to dig deeper :)
If not, I'll close this issue on Monday

**Comment by terenc3t** [comment]
That's perfect. Answered all my questions. Thanks a lot!
