### ISSUE TITLE
question on epoch transitions

### ISSUE THREAD

**Issue by terenc3t** [ethereum/beacon_chain#55]
**1.)**

>  for all slots `s` in `(epoch_number - 2) * EPOCH_LENGTH ... (epoch_number - 1) * EPOCH_LENGTH - 1`

Is that correct? It seems odd
```
# Assume we are in our 3rd epoch cycle
(3 - 2) * 64 = 64
(4 - 1) * 64 - 1 = 191 
```

**2.)**  

> Determine the total set of validators that voted for that block at least once

How do we determine that? by looking through that epoch's incoming block's `attestations` field? Do we just loop through the `attester_bitfield` and count the number of voted attester?

**3.)**  
> Determine the total balance of these validators

How do we do that? How do we correlate `attester_bitfield` to `valiator_record`? that's the only place to get validator balance right?

**Comment by djrtwo** [comment]
1) Your example math is wrong -- `epoch_number` should be the same for each
```python
# Assume we are in our 3rd epoch cycle
(3 - 2) * 64 = 64
(3 - 1) * 64 - 1 = 127 
```

2) Loop through all of the `active_state.pending_attestations`, if the block in question is included in the `oblique_parent_hashes` mark the validators from that attestation's bitfield as having voted for the block.

3) From step 2, you should have validator indices that you can use to check into the `crystallized_state.validators` array and sum the balances from there. Note, validator indices are fixed. A validator at position N is always to be at position N.
