### ISSUE TITLE
EVM validator deposit contract

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#6]
# Issue
The beacon chain design requires a contract on the main chain for one-way deposits and validator config initialization.

# Proposed Implementation
This contract should be written in Vyper, and should probably live in /contracts and be tested with eth-tester/web3.py.

- create `deposit` function with the following arguments
  - pubkey (bytes)
  - withdrawal_shard_id (int)
  - withdrawal_addr (address)
  - randao_commitment (bytes32)
- make `deposit` a `payable` function. `assert msg.value == 32ETH`
- `deposit` function prevents multiple deposits for same `pubkey`
- `deposit` emits a log with all params

**Comment by ChihChengLiang** [comment]
would like to work on this

**Comment by djrtwo** [comment]
Go for it!
Probably can use the casper code base as a reference for testing setup and stuff.

I've been thinking this should probably live in /contracts separate from /beacon_chain. Tests can live in tests/contracts. I think we might need a larger reorg than that to fully clean things up, but this should be a good place to start for this PR.
