### ISSUE TITLE
Add proposer verification to block validity rules

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#63]
# Issue
The implementation does not currently verify the "proposer" of the block as described in the following:

>Verify that the slot % len(get_indices_for_slot(crystallized_state, active_state, slot-1)[0])'th attester in get_indices_for_slot(crystallized_state, active_state, slot-1)[0]is part of at least one of the AttestationRecord objects; this attester can be considered to be the proposer of the block.

# Proposed implementation
* `process_block` should validate the presence of the proposer in the block as described above.

**Comment by hwwhww** [comment]
According to the discussion on gitter, the condition above may be only part of **proposer verification**. The missing half is the proposer should sign the block.

Do you think the condition in the current spec is okay to implement now? I can start to sort out this one. :)

**Comment by djrtwo** [comment]
Been talking with V. Leaning towards a model where the proposer creates and
then attests to the block in the same slot. This is different than current
spec. Hold off for a couple days I'd say

**Comment by djrtwo** [comment]
This has not yet been updated/resolved in the spec. Checking in on it

**Comment by djrtwo** [comment]
closing in favor of https://github.com/ethereum/beacon_chain/issues/85
