### ISSUE TITLE
Add state roots validation

### ISSUE THREAD

**Issue by hwwhww** [ethereum/beacon_chain#73]
### Issue
The state roots validation is not part of the current spec or codebase.

### How to fix it
~~After the spec is revised, we add the state roots validation between [here L349](https://github.com/ethereum/beacon_chain/blob/a84076d548a9a6519834b8a0576485a02548083d/beacon_chain/state/state_transition.py#L342-L350):~~ 

It should be done outside state transtion function. There are some different processes;
when the validator applies lookahead via `get_new_shuffling`, check if ze is the proposer or validator of a certain slot:

* if is an attester
    * [stub] make and broadcast the crosslink
    * make the attestation
    * [stub] broadcast

* elif is_proposer and time to propose block of the certain slot:
    * collect attestations
    * propose the block
    * `compute_state_transition`
    * **set state roots of the block**
    * [stub] broadcast the block

On receiving a new block
* `compute_state_transition`
* **validate state roots**
* [stub] apply fork choice rule

We can wrap the `is_proposer...` process and modify `mock_validator_record` now to get some more genenal API that can be used for both the real client and the tests.

**Comment by hwwhww** [comment]
@djrtwo I updated the issue description. Could you take a look to confirm the abstract processes are correct? Thanks. :)

**Comment by djrtwo** [comment]
for attester:
- the attestation serves as the crosslink so I don't think this should be considered separate (attestation includes shard_block_hash)
- We could add two steps before "make the attestation"
    - "[stub] find recent shard_block_hash"
    - "compute head of beacon chain"

for proposer:
- proposer is also attester of the same slot. in terms of flow, they should build their block first and then do the attestation work (in which the block they just built will be head and thus attested to). Then both should be broadcast

Note! The computing and setting of state roots can be found here in testing setup for reference.
https://github.com/ethereum/beacon_chain/blob/master/tests/state/conftest.py#L365-L378
