### ISSUE TITLE
add `justified_slot` and `justified_block_hash` to attestation

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#74]
# Issue
v2.1 spec now has new fields (`justified_slot` and `justified_block_hash`) in `Attestation` and some logic regarding these fields when processing attestations.

# Proposed Implementation
- add `justified_slot` and `justified_block_hash` to `Attestation`
- When validating attestation,
> Verify that the justified_slot and justified_block_hash given are in the chain and are equal to or earlier than the last_justified_slot in the crystallized state.

**Comment by hwwhww** [comment]
closed via #123
