### ISSUE TITLE
Add dynasty change

### ISSUE THREAD

**Issue by djrtwo** [ethereum/beacon_chain#89]
# Issue
Basic logic for dynasty change was added to v2.1. Add it!

# Proposed implementation
- follow spec. steps are primarily contained at end of state recalculations.

**Comment by terenc3t** [comment]
Here is my implementation for pryzm. Feel free to take a look 😃 

https://github.com/prysmaticlabs/prysm/pull/498

**Comment by djrtwo** [comment]
nice! Just got my PR up too :)

**Comment by hwwhww** [comment]
close via #90
