### ISSUE TITLE
Question on Shuffling Algorithm

### ISSUE THREAD

**Issue by terenc3t** [ethereum/beacon_chain#9]
Is there a write up or a spec on how the shuffling algorithm works? I checked https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?view and still have troubles understanding this part of the algorithm:

```python
        for pos in range(0, 30, 3):
            m = int.from_bytes(source[pos:pos+3], 'big')
            remaining = validator_count - i
            if remaining == 0:
                break
            if validator_count < rand_max:
                replacement_pos = (m % remaining) + i
                o[i], o[replacement_pos] = o[replacement_pos], o[i]
                i += 1
```

**Comment by djrtwo** [comment]
Let me now if this pseudocode helps:
```python
while not_all_validator_positions_shuffled:
    source = get_pseudorandom_32_bytes(source)
    for every_three_bytes in source:
        m = convert_three_bytes_to_int(current_three_bytes)
        remaining = the_number_of_validators_left_to_shuffle
        if none_remaining:
            break
        replacement_pos = get_replacement_position_for_i(m, i)
        swap(i, replacement_pos)
        go_to_next_position()  # i += 1
```

Also, it looks like `if validator_count < rand_max` isn't actually doing anything.

**Comment by terenc3t** [comment]
> EDIT: note that 3 bytes is 24 bits (int24) which is the assumed maximum number of active validators in the system. Actually, this algorithm requires that maximum be 2^23 validators.

Ahh! That's why the following is asserted. Got it! Your pseudocode helped a lot. Thanks @djrtwo! 
```
assert validator_count <= MAX_VALIDATORS
```
