### ISSUE TITLE
Add document for Simple Serialization (SSZ)

### ISSUE THREAD

**Issue by hwwhww** [ethereum/beacon_chain#99]
### What's wrong
No specification for SSZ for auditing or verification.

### How can it be fixed
Add document on [ssz/README.md](https://github.com/ethereum/beacon_chain/blob/master/ssz/README.md)

**Comment by Poseyy** [comment]
How much detail is desired for this? I think I will try making something with a decent bit of detail and then a reviewer can axe details as necessary.

**Comment by paulhauner** [comment]
This might be a useful resource: https://github.com/sigp/lighthouse/tree/ssz-readme/ssz

It's a work in progress from one of our team members as we build out a Rust impl.

Feel free to use anything you want from it!

**Comment by hwwhww** [comment]
@paulhauner That's awesome! What do you think of concentrating our resources on the "common" part? e.g., Design rationale and how SSZ works. We can add the common document under [Ethereum wiki](https://github.com/ethereum/wiki/wiki).

@Poseyy Thank you so much! I think Lighthouse has a great outline of the document. The things that we can append in a common document are (i) the design rationale - maybe recap what Vitalik said in the eth2.0 call last week. (ii) More example of the serialized result.
On the other hand, we want to have an instruction on how to use Python SSZ APIs especially.

**Comment by paulhauner** [comment]
Thanks @hwwhww, we'd be more than happy to collaborate.

I'm not exactly sure what you mean by "concentrating our resources", though. Would you mind elaborating please?

**Comment by paulhauner** [comment]
Ok, got it, thanks.

This issue relates to Python specifics and we can talk about the "common" document in another channel :)

**Comment by Poseyy** [comment]
@hwwhww Sounds great, will do!
